services:

  sglang-env:
    build:
      context: ./image
      args:
        HF_TOKEN: ${TOKEN}
        VSCODE_COMMIT_ID: ${VSCODE_COMMIT_ID}
    deploy:
      resources:
        limits:
          cpus: '15'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${TOKEN}
      - MKL_NUM_THREADS=15
      - OPENBLAS_NUM_THREADS=15
      - TORCH_NUM_THREADS=4
      - MAX_JOBS=1                      # 限制 nvcc/cicc 最大同時編譯任務數
      - TRITON_MAX_CPU_THREADS=4        # 限制 Triton JIT 編譯線程數
      - OMP_NUM_THREADS=4               # 限制 OpenMP 線程數
    volumes:
      - ./cache:/root/.cache:rw
    ports:
      - "11434:11434"
      - "222:22"
    entrypoint: >
      sglang serve   --model-path /root/.cache/huggingface/hub/models--RadixArk--Qwen3.8-Flash-Next-NVFP4/snapshots/7b719225242aacd3dbd3f9407468c2ee9a9d2594   --tp 1   --quantization modelopt_fp4   --fp4-gemm-backend flashinfer_cutlass   --page-size 64   --chunked-prefill-size 4096   --context-length 262144   --speculative-algorithm NEXTN   --speculative-num-steps 3   --speculative-eagle-topk 1   --speculative-num-draft-tokens 4   --max-running-requests 8   --max-mamba-cache-size 40   --tool-call-parser qwen3_coder   --reasoning-parser qwen3   --mem-fraction-static 0.85   --host 0.0.0.0   --port 11434   --ple-offload-embedding   --ple-offload-backend file   --ple-offload-dir /tmp/ple
