services:

  sglang-env:
    build:
      context: ./image
      args:
        HF_TOKEN: ${TOKEN}
        VSCODE_COMMIT_ID: ${VSCODE_COMMIT_ID}
    deploy:
      resources:
        limits:
          cpus: '15'
          memory: 100G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${TOKEN}
    volumes:
      - ./cache:/root/.cache:rw
    ports:
      - "222:22"
      - "11434:11434"
    #command: tail -f /dev/null
    #entrypoint: >
    #python3.12 -m vllm.entrypoints.openai.api_server --model openai/gpt-oss-20b --gpu-memory-utilization 0.9 --max-model-len 1024 --max-num-seqs 1 --port 8000

